[package]
name = "rust_basics"
version = "0.1.0"
edition = "2024"

[dependencies]
fern = "0.7.1"
log = "0.4.27"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features= ["fmt", "json", "env-filter"] }

